### ISSUE TITLE
not able to see phone number section in a particular user's profile 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#125]
![image](https://user-images.githubusercontent.com/58812881/84644449-d07cb400-af1c-11ea-93e0-0e32cf3ddaf7.png)

**Comment by Avinash-ecb** [comment]
this issue is fixed now
when you have phone number and see your own profile
![image](https://user-images.githubusercontent.com/46588125/84653373-ebeebb80-af2a-11ea-890f-2db99465d7cb.png)

when you have no phone number and see your own profile
![image](https://user-images.githubusercontent.com/46588125/84653575-4daf2580-af2b-11ea-826a-0c7884715c69.png)
 

when other see your profile and you have phone number
![image](https://user-images.githubusercontent.com/46588125/84653432-06289980-af2b-11ea-926e-e3f41628a1b1.png)

when you have no phone number and other see your profile then section can't show

**Comment by harshitaexpcon** [comment]
![image](https://user-images.githubusercontent.com/66782635/84731030-3fa5e700-afb5-11ea-8e9d-78afeeb300ef.png)
